### ISSUE TITLE
Code for video 5

### ISSUE THREAD

**Issue by lievcin** [koaning/spacy-youtube-material#4]
Hi Vincent!
Many thanks for the videos, they're very helpful :)
I was wondering when you might be able to publish the code for the latest video which uses Spacy 3.
Thank you!

**Comment by koaning** [comment]
Ah yes! It's published under a new repo: https://github.com/koaning/proglang-project I'll add a comment to the readme too!

**Comment by lievcin** [comment]
Sweet, thanks a lot! @koaning, moving to a project and it's handy to have a template to follow the first time!
