### ISSUE TITLE
03-labelling-evaluation.ipynb | have_label.txt

### ISSUE THREAD

**Issue by kapilok2014** [koaning/spacy-youtube-material#5]
Hi Vincent,

Thanks for a great Spacy series ... tremendous learning. Kudos !!
I was wondering if you could add the - have_label.txt file to the repo, so I can just load it and run.
We typically label with prodigy, so not quite looking to label manually with excel.

Thanks,
Kapil

**Comment by koaning** [comment]
I should admit that when switching employers I forgot to make a backup of my initial disk which means we did loose some data for this project. 

Having said that, there's a new repo that contains plenty of labels here: https://github.com/koaning/proglang-project

**Comment by kapilok2014** [comment]
Thanks. Will check it out.
Cheers.
