### ISSUE TITLE
Code for video 5

### ISSUE THREAD

**Issue by JBOE22175** [koaning/spacy-youtube-material#6]
Hi Vincent,
it would be helpful if you could upload the code for video 5. 
There was already an issue about this topic. But your answer was a link to the video 6.
I think code for video 5 is still missing.

**Comment by koaning** [comment]
The code for video 5 was on my employer's laptop, the disk of which has been wiped clean. 

That code is also old though. Video 6 and onwards will use spaCy 3.x.
